version: "3"

services:
  webapp:
    build: .
    container_name: webapp
    ports: 
      - "80:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlServer
    environment:
        SA_PASSWORD: "Marine7815@@"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
