version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports: 
      - "80:80"
    depends_on:
      - sqlServer
      
  sqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
    container_name: 'sqlServer'
    hostname: sqlServer
    environment:
        SA_PASSWORD: "Marine7815@@"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
