services:
  webapp:
    build: .
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Marine7815@@"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
