version: "3"

services:
  sqlserver:
    container_name: sqlserver
    build: 
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    tty: true

    depends_on:
      - webapp

      
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "80:80"
      
  
